server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|](?!-)[a-zA-Z0-9][a-zA-Z0-9_.-])+)
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # Application logs from the backend service
  - job_name: backend-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          service: gmail-search-backend
          __path__: /var/log/backend/*.log
    pipeline_stages:
      - timestamp:
          format: RFC3339
      - labels:
          level:
          service:

  # Agent-specific logs
  - job_name: agent-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: agents
          __path__: /var/log/agents/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            agent: agent
            message: message
            timestamp: timestamp
      - timestamp:
          format: RFC3339
          source: timestamp
      - labels:
          level:
          agent:
