server:
  http_listen_port: 3100

common:
  path_prefix: /loki

storage_config:
  boltdb:
    directory: /loki/index

  filesystem:
    directory: /loki/chunks

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://127.0.0.1:9093

